CI:
    - .github/**
CMake:
    - "**CMakeLists.txt"
    - cmake/**
OpenGL:
    - src/contour/opengl/*.cpp
    - src/contour/opengl/*.h
"VT: backend":
    - src/terminal/*.cpp
    - src/terminal/*.h
"VT: renderer":
    - src/vtrasterizer/*.cpp
    - src/vtrasterizer/*.h
documentation:
    - "**/*.md"
    - docs/**
fonts:
    - src/text_shaper/*.cpp
    - src/text_shaper/*.h
frontend:
    - src/contour/*.cpp
    - src/contour/*.h
test:
    - src/**/*_test.cpp
