name: C/C++ CI

on:
  push:
    branches:
    - master
    - wip
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: deps
      run: vcpkg install freetype fontconfig glew glfw3 glm harfbuzz
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Release
    - name: make
      run: make
    - name: test
      run: ./src/terminal/terminal_test

  build:
    runs-on: osx-latest
    steps:
    - uses: actions/checkout@v1
    - name: deps
      run: brew update && brew install install freetype fontconfig glew glfw3 glm harfbuzz
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Release
    - name: make
      run: make
    - name: test
      run: ./src/terminal/terminal_test

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: deps
      run: apt install libfreetype6-dev libglew-dev libglfw3-dev libglm-dev libfontconfig1-dev libharfbuzz-dev
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Release
    - name: make
      run: make
    - name: test
      run: ./src/terminal/terminal_test
